swagger: '2.0'
info:
  title: API
  description: API documentation
  version: v1
host: 127.0.0.1:8000
schemes:
- http
basePath: /
consumes:
- application/json
produces:
- application/json
securityDefinitions:
  Basic:
    type: basic
security:
- Basic: []
paths:
  /coordinates/:
    get:
      operationId: coordinates_list
      description: ''
      parameters:
      - name: coordinates
        in: query
        description: Coordinates
        type: string
      responses:
        '200':
          description: ''
      tags:
      - coordinates
    parameters: []
  /login/:
    post:
      operationId: login_create
      description: ''
      parameters:
      - name: data
        in: body
        required: true
        schema:
          required:
          - username
          - password
          type: object
          properties:
            username:
              description: User name
              type: string
            password:
              description: User password
              type: string
      responses:
        '201':
          description: ''
          schema:
            required:
            - username
            - password
            type: object
            properties:
              username:
                description: User name
                type: string
              password:
                description: User password
                type: string
      tags:
      - login
    parameters: []
  /register/:
    post:
      operationId: register_create
      description: ''
      parameters:
      - name: data
        in: body
        required: true
        schema:
          required:
          - username
          - password
          type: object
          properties:
            username:
              description: User name
              type: string
            password:
              description: User password
              type: string
      responses:
        '201':
          description: ''
          schema:
            required:
            - username
            - password
            type: object
            properties:
              username:
                description: User name
                type: string
              password:
                description: User password
                type: string
      tags:
      - register
    parameters: []
definitions: {}
